# Generated by Django 3.2.3 on 2021-06-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0010_alter_postimages_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='posts',
            new_name='post',
        ),
    ]
